name: pyflexplot
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - alsa-lib=1.2.3
  - appdirs=1.4.4
  - astroid=2.8.5
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.12b0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bump2version=1.0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cartopy=0.20.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfgv=3.3.1
  - cftime=1.5.1.1
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - codespell=2.1.0
  - colorama=0.4.4
  - cryptography=35.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.1.0
  - distlib=0.3.3
  - docutils=0.16
  - editdistance-s=1.0.0
  - expat=2.4.1
  - filelock=3.3.2
  - flake8=4.0.1
  - flake8-black=0.2.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.10.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.0
  - glib-tools=2.70.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.2
  - identify=2.3.6
  - idna=3.1
  - imagesize=1.3.0
  - importlib-metadata=3.10.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipdb=0.13.9
  - ipython=7.30.1
  - isort=5.10.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.3
  - jpeg=9d
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm9=9.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - livereload=2.6.3
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - more-itertools=8.11.0
  - munkres=1.1.4
  - mypy=0.910
  - mypy_extensions=0.4.3
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - ncurses=6.2
  - netcdf4=1.5.8
  - nodeenv=1.6.0
  - nspr=4.32
  - nss=3.72
  - numpy=1.21.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - parso=0.8.2
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - platformdirs=2.3.0
  - pluggy=0.13.1
  - pre-commit=2.16.0
  - proj=8.2.0
  - prompt-toolkit=3.0.22
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.11.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - pygments=2.10.0
  - pylint=2.11.1
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pypdf2=1.26.0
  - pyproj=3.2.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - qt=5.12.9
  - readline=8.1
  - regex=2021.11.10
  - requests=2.26.0
  - rope=0.22.0
  - rstcheck=3.3.1
  - scipy=1.7.3
  - setuptools=59.1.1
  - shapely=1.8.0
  - six=1.16.0
  - snowballstemmer=2.1.0
  - sphinx=4.3.1
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - tbb=2021.4.0
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - tox=3.24.4
  - traitlets=5.1.1
  - typed-ast=1.5.0
  - types-toml=0.10.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - virtualenv=20.4.7
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
