name: pyflexplot
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.13
  - alsa-lib=1.2.8
  - anaconda-client=1.11.0
  - anyio=3.6.2
  - appdirs=1.4.4
  - astroid=2.14.2
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - black=23.1.0
  - boa=0.14.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cartopy=0.21.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - cftime=1.6.2
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - clyent=1.2.2
  - codespell=2.2.2
  - colorama=0.4.6
  - conda=22.11.1
  - conda-build=3.23.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - contourpy=1.0.7
  - cryptography=39.0.1
  - curl=7.88.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.1.1
  - dill=0.3.6
  - distlib=0.3.6
  - docutils=0.17.1
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.9.0
  - flake8=6.0.0
  - flake8-black=0.3.5
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - geographiclib=1.52
  - geopy=2.3.0
  - geos=3.11.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - glob2=0.7
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - identify=2.5.18
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=4.13.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipdb=0.13.11
  - ipython=8.10.0
  - isort=5.12.0
  - jack=1.9.22
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_core=5.2.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.9.0
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.88.1
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm15=15.0.7
  - libmamba=1.1.0
  - libmambapy=1.1.0
  - libnetcdf=4.9.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libsndfile=1.2.0
  - libsolv=0.7.22
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - livereload=2.6.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.1.0
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mpg123=1.31.2
  - munkres=1.1.4
  - mypy=1.0.1
  - mypy_extensions=1.0.0
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbformat=5.7.3
  - ncurses=6.3
  - netcdf4=1.6.2
  - nodeenv=1.7.0
  - nspr=4.35
  - nss=3.88
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.0.8
  - packaging=23.0
  - parso=0.8.3
  - patch=2.7.6
  - patchelf=0.17.2
  - pathspec=0.11.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - pre-commit=3.0.4
  - proj=9.1.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pybind11-abi=4
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.5
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pylint=2.16.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pypdf2=1.28.4
  - pyproj=3.4.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=7.2.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=4.0
  - python_abi=3.11
  - pytoolconfig=1.2.5
  - pytz=2022.7.1
  - pyyaml=6.0
  - qt-main=5.15.8
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - rich=13.3.1
  - ripgrep=13.0.0
  - rope=1.7.0
  - rstcheck=6.1.1
  - rstcheck-core=1.0.3
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scipy=1.10.1
  - setuptools=65.6.3
  - shapely=2.0.1
  - shellingham=1.5.1
  - sip=6.7.7
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.2.post1
  - sphinx=5.3.0
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.6
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - typer=0.4.2
  - types-docutils=0.18.3
  - types-setuptools=67.4.0.1
  - types-toml=0.10.8.5
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.14
  - virtualenv=20.19.0
  - watchgod=0.8.2
  - wcwidth=0.2.6
  - wheel=0.38.4
  - wrapt=1.14.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=3.14.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - copier==7.0.1
      - dunamai==1.16.0
      - flake8-pyproject==1.2.2
      - iteration-utilities==0.11.0
      - jinja2-ansible-filters==1.3.2
      - mistune==2.0.5
      - plumbum==1.8.1
      - pyyaml-include==1.3
      - questionary==1.10.0
      - sphinx-mdinclude==0.5.3
